---
title: "MAGERI benchmark using reference standard DNA library"
author: "Mikhail Shugay"
date: "December 1, 2016"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load metadata

```{r}
df.vmeta <- read.table("hd734_variant_metadata.txt", sep="\t", header=T) # variants observed in HD734 and covered by our primers
df.smeta <- read.table("sample_metadata.txt", sep="\t", header=T) # metadata for amplicon sequencing samples
```

VCF parsing function

```{r}
library(stringr)
library(pROC)
library(ggplot2)
library(ggbeeswarm)
library(dplyr)

read_vcf <- function(file_name) {
  .vcf <- read.table(file_name, header = F, sep = "\t", stringsAsFactors = F)
  colnames(.vcf) <- c("chromosome", "position",	"skip1", "from", "to", "qual", "skip2", "info", "skip3", "skip4")
  .vcf$skip1 <- NULL
  .vcf$skip2 <- NULL
  .vcf$skip3 <- NULL
  .vcf$skip4 <- NULL
  
  .vcf$qual <- as.integer(.vcf$qual)
  .vcf <- subset(.vcf, nchar(from) == 1 &
                   nchar(to) == 1 & !is.na(qual)) # no indels
  
  .infosplit <- str_split_fixed(.vcf$info, regex("[=;]"), 15)[,c(2, 4, 12, 14)]
  
  .vcf$coverage <- as.numeric(.infosplit[,1])
  .vcf$frequency <- as.numeric(.infosplit[,2])
  .vcf$bb.a <- as.numeric(.infosplit[,3])
  .vcf$bb.b <- as.numeric(.infosplit[,4])
  .vcf$info <- NULL
  
  .vcf$count <- as.integer(round(.vcf$coverage * .vcf$frequency))
  
  .vcf
}

head(read_vcf("p126.h4_2_ballast_m1.vcf"))
```

Read samples with HD734 standard DNA and control human DNA, append metadata

```{r}
df <- data.frame()

read_vcf_with_metadata <- function(file_name, primer_set, replica, ratio, type) {
  .vcf <- read_vcf(file_name)
  .vcf <- merge(.vcf, df.vmeta, all.x = type != "standard", all.y = F)
  .vcf$known.frequency <- .vcf$known.frequency * ratio
  .vcf$known.frequency[is.na(.vcf$known.frequency)] <- 0
  .vcf$primer_set <- primer_set
  .vcf$replica <- primer_set
  .vcf$type <- type
  
  .vcf <- subset(.vcf, frequency < 0.4 & count > 0) # remove alleles in control
  
  .vcf
}

for (i in 1:nrow(df.smeta)) {
  df <- with(df.smeta, rbind(df, 
                             read_vcf_with_metadata(paste(prefix[i], "vcf", sep="."), 
                                                    primer_set[i],
                                                    replica[i],
                                                    ratio[i],
                                                    type[i])))
}
```

Group observed variants into tiers

```{r}
df$tier <- cut(df$known.frequency, c(-1, 0, 0.009, 0.02, 1))
levels(df$tier) <- c("error", "0.1%", "1%", "5%")
summary(df$tier)
```

Number of detected variants and sampling

```{r}
df.v.summary <- df.vmeta
df.v.summary$known.frequency <- df.v.summary$known.frequency * 0.1 # 1:9 diluted samples
df.v.summary$ratio <- "1:10"
df.v.summary.2 <- df.vmeta
df.v.summary.2$ratio <- "1:1"
df.v.summary <- rbind(df.v.summary, df.v.summary.2)
df.v.summary$tier  <- cut(df.v.summary$known.frequency, c(-1, 0, 0.009, 0.02, 1))
levels(df.v.summary$tier) <- c("error", "0.1%", "1%", "5%")

print(df.v.summary)

df.v.summary <- df.v.summary %>% 
  group_by(tier) %>%
  summarise(total = n())
df.v.summary$total <- 2 * df.v.summary$total # we have 2 independent experiments

df.v.summary <- merge(df.v.summary,
                      df %>% group_by(tier) %>%
                        summarise(found = n(), 
                                  detect.prob.m = mean(1-exp(-frequency * coverage)),
                                  detect.prob.sd = sd(1-exp(-frequency * coverage))))

df.v.summary$detection.prob.lb <- with(df.v.summary,
                                       detect.prob.m - 1.96*detect.prob.sd - 5e-3)
df.v.summary$detection.prob.ub <- with(df.v.summary,
                                       detect.prob.m + 1.96*detect.prob.sd)

df.v.summary$detection.prob.ub <- ifelse(df.v.summary$detection.prob.ub > 1,
                                         1, 
                                         df.v.summary$detection.prob.ub )

library(scales)

fig3 <- ggplot(df.v.summary, aes(x=tier)) +
  geom_bar(stat="identity", aes(y=detection.prob.ub), fill = "grey70", width=0.5)+
  geom_bar(stat="identity", aes(y=detection.prob.lb), fill = "white")+
  geom_point(aes(y = found/total), size = 5, color="red", shape="+") +
  geom_text(aes(y = found/total - 0.05, label = paste(found, total, sep="/"))) +
  scale_y_continuous("Detection rate", labels=percent) + 
  xlab("Variant tier") +
  theme_bw() +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_blank())

save(file = "../figures/fig3.Rda", fig3)

fig3
```

Quality score and error P-values

```{r}
df.e <- df %>% 
  filter(type == "blank") %>%
  mutate(true.p.value = -10 * log10(1 - (rank(frequency) - 0.5) / n()))

fig4 <- ggplot(df.e, aes(true.p.value, qual)) + 
  geom_abline(slope = 1, intercept = 0, linetype = "dashed") +
  geom_smooth(color="red", fill="grey", alpha=0.5) + 
  scale_x_continuous("-10 log10 P-value", limits = c(0, 40)) +
  scale_y_continuous("Q score", limits = c(0, 40)) +
  theme_bw()

save(file = "../figures/fig4.Rda", fig4)

fig4
```

Frequency of variants and errors

```{r}
fig5 <- ggplot(df, aes(x=frequency, color = tier)) +
  geom_density(aes(fill=tier), alpha=0.7) + 
  ylab("Density") +
  scale_x_log10("Frequency") + 
  scale_color_brewer("Variant tier", palette = "Set1") +
  scale_fill_brewer("Variant tier", palette = "Set1") +
  theme_bw()

save(file = "../figures/fig5.Rda", fig5)

fig5
```

Variant quality scores

```{r}
fig6 <- ggplot(df,aes(tier, qual, fill=tier)) + 
  geom_hline(yintercept = 13.0103, linetype ="dotted") +
  geom_hline(yintercept = 20.0103, linetype ="dashed") +
  geom_quasirandom(varwidth = T, shape=21, color="grey10") +
  annotate("text", label = "p < 0.05", x=4.3,y=13.0103+2) +
  annotate("text", label = "p < 0.01", x=4.3,y=20.0103+4) +
  scale_fill_brewer("", palette = "Set1", guide=F) +
  xlab("Variant tier") + ylab("Q score") +
  theme_bw()

save(file = "../figures/fig6.Rda", fig6)

fig6
```

ROC curve for rare variants

```{r}
df.1 <- subset(df, tier %in% c("error", "0.1%"))
df.1$type <- ifelse(df.1$tier == "error", 0, 1)

make_roc <- function(rocobj, type) {
  .df.roc <- data.frame(spec = seq(0, 1, 0.01))
  sens.ci <- ci.se(rocobj, specificities = .df.roc$spec)

  .df.roc$sens.lo <- sens.ci[,1]
  .df.roc$sens.me <- sens.ci[,2]
  .df.roc$sens.hi <- sens.ci[,3]
  .df.roc$type <- type
  
  .df.roc 
}

rocobj <- roc(type ~ qual, df.1, ci=T)
print(rocobj)
df.roc <- make_roc(rocobj, "Q score")
rocobj <- roc(type ~ frequency, df.1, ci=T)
print(rocobj)
df.roc <- rbind(df.roc, make_roc(rocobj, "Frequency"))

fig7 <- ggplot(df.roc, aes(x=spec)) +
  geom_ribbon(aes(ymin=sens.lo, ymax=sens.hi, group=type), fill="grey", alpha=0.5) +
  geom_abline(slope = 1, intercept = 1, linetype = "dashed") +
  geom_line(aes(y=sens.me, color = type)) +
  scale_x_reverse("Specificity") +
  scale_y_continuous("Sensitivity", limits=c(0,1)) +
  scale_color_brewer("Threshold", palette = "Set1") +
  theme_bw()

save(file = "../figures/fig7.Rda", fig7)

fig7
```

